### ISSUE TITLE
RTL: layered navigation module range filter

### ISSUE THREAD

**Issue by firstred** [thirtybees/blocklayered#1]
The range filter need support for RTL.
This is more than just css, because part of it comes from JS.
example

RTL reads from right to left but digit consider LTR which place the currency symbol wrong.

From: thirtybees/thirtybees#230

**Comment by Traumflug** [comment]
@yaniv14 provided this picture:

![grafik](https://user-images.githubusercontent.com/318581/41381609-e2bc9c7a-6f68-11e8-9fdb-71c3c12f5410.png)

**Comment by Traumflug** [comment]
Steps to reproduce:

- Install a shop using the English language, for country Israel, with demo products.
- View a category, which also brings up layered navigation.

This is how it looks when switched to English (on the left side):

![grafik](https://user-images.githubusercontent.com/318581/41792296-acc97d6c-7658-11e8-86c0-f9256fbf0ecc.png)

This is how it looks when switched to Hebrew (on the right side):

![grafik](https://user-images.githubusercontent.com/318581/41792340-d1f19764-7658-11e8-94e1-0a8889926781.png)

Neither looks like the reported picture, so the million dollar question is, is the price display now right? Can you help, @yaniv14?

**Comment by yaniv14** [comment]
The way it is right now is almost perfect.
it looks like in your picture which is fine enough.
The only small thing that might be better is if the lower number will be on the left side.
Even do its RTL language, still numbers are read from left to right.
But this is really something minor and can stay the way it is.
My original issue was a year ago, and a lot changed since.

**Comment by Traumflug** [comment]
Like this?

![grafik](https://user-images.githubusercontent.com/318581/41809070-9c633b40-76e7-11e8-98f6-eb49c223cea7.png)

Commit in *blocklayered*: https://github.com/thirtybees/blocklayered/commit/4ae8fcfa950f4078960a96370f3fdd7e18345688

Commit in *community-theme-default* (which is what people usually see): https://github.com/thirtybees/community-theme-default/commit/0aa28a7214db4f4c897e6efb4d2c830d9a199c9f

**Comment by yaniv14** [comment]
Yes, but once you fixed that, we will need to modify the slider it self (css & js maybe?) to comply with left to right slides.
ohh, my mistake. I see that it does works fine with the lowest amount on the left side of the slider.
I think its perfect the way you fixed it.

**Comment by Traumflug** [comment]
Excellent. Thank you for your help!
