### ISSUE TITLE
The name of SelectedFilters are not translated back to english on next pages (pagination).

### ISSUE THREAD

**Issue by matpoppl** [thirtybees/blocklayered#2]
For example in Polish language the word "price" is translated to "cena".
So when I set price range filter to "from 31.97 to 52.06" the URL query parameter look like this "cena-31.97_52.06"

The problem is in BlockLayered::getSelectedFilters() where the word "cena" isn't translated back to "price" so it isn't used in SQL query.

For page-1 it works fine, because it isn't depending on "selected_filters" but "layered_price_slider" so the translation isn't necessary.

But for next pages (like page-2) the XHR parameters are looking differently and so the "BlockLayered::getSelectedFilters()" behaves differently.

The diffrence is in the first IF() statement
```php
if (strpos($_SERVER['SCRIPT_FILENAME'], 'blocklayered-ajax.php') === false || Tools::getValue('selected_filters') !== false) {
// HERE page-2
} else {
// HERE page-1
}
```
![page-1](https://user-images.githubusercontent.com/10683466/34561010-78043526-f148-11e7-8133-2926a715995b.gif)
![page-2](https://user-images.githubusercontent.com/10683466/34561012-781f8754-f148-11e7-9996-8beaaadbf5ed.gif)

**Comment by Traumflug** [comment]
First, thanks for reporting this issue.

That said, I struggle a bit to reproduce this issue. With or without pretty URLs enabled, `selected_filters` is just `/page-2`, without `price` or `cena` or anything in front of it (tested in a shop providing English and Hebrew):

![bildschirmfoto von 2018-06-22 20-45-51](https://user-images.githubusercontent.com/318581/41793750-5be67080-765d-11e8-93f7-ffbecb45f303.png)

Can you still reproduce the issue with *thirty bees 1.0.4* and *blocklayered 3.0.1*, @matpoppl ? If yes, a list of steps to reproduce would be excellent.

**Comment by Traumflug** [comment]
Apparently no longer a problem. Please don't hesitate to open another issue if there's something left.

**Comment by matpoppl** [comment]
Sorry for the delay. It is still a problem in 1.0.4 (clean install).
If You are using a clean install also please be sure to decrease the about of products per page (PS_PRODUCTS_PER_PAGE) to some small value (like 3) that will force to initiate the pager.

I have a test installation here http://prestashop-tb1.nyloncoffee.pl/coffee-and-tea where PS_PRODUCTS_PER_PAGE=3

And there are 6 products
1. test 12,30 zł
2. Tin Cup 15,38 zł
3. Mug 17,84 zł
4. Tea 19,68 zł
5. Coffee 22,14 zł
6. Honey 27,06 zł 

You can move the price slider to 16zł and go to Page number 2. That will cause to reset/break the filter.

**Comment by Traumflug** [comment]
Got it now. Can't get such a mistaken `selected_filters` parameter, but I can see the URL changing in an unfortunate way. Also see the filter resetting when going to the next page.

Looks like it's a mistake to translate this word at all. Will look closer into this tomorrow.

**Comment by Traumflug** [comment]
Here's a patch which solves part of the problem. Actually, the *blocklayered* module does it fine, but the *community-default-theme* override messes it up. Which is why this patch should be applied in the theme, not in the module.

```diff
------------------- js/modules/blocklayered/blocklayered.js -------------------
index e60e3f3..9da4f91 100644
@@ -319,7 +319,7 @@ function reloadContent(paramsPlus) {
           // Check if slider is enable & if slider is used
           if (typeof $slider.slider('values', 0) !== 'object') {
             if ($slider.slider('values', 0) !== $slider.slider('option', 'min') || $slider.slider('values', 1) !== $slider.slider('option', 'max')) {
-              window.current_friendly_url += '/' + blocklayeredSliderName[sliderType] + '-' + $slider.slider('values', 0) + '-' + $slider.slider('values', 1);
+              window.current_friendly_url += '/' + sliderType + '-' + $slider.slider('values', 0) + '-' + $slider.slider('values', 1);
             }
           }
         } else if ($sliderRangerMin.length) {

```

Why thirty bees duplicates code by having overrides in the default theme? No idea.

This patch ~~doesn't~~ solves the language-specific part of the problem, still sliders don't work as expected. If you move the slider and then switch to the next page, the filter still resets. If you move the filter to 25 zl, release the mouse, then again to 20 zl and then go to the next page, the filter isn't reset to no filter, but to the range of the first move. Updating these pagination URLs gets delayed somehow.

**Comment by Traumflug** [comment]
Right. Filters as well as pagination should work fine now when using community theme overrides.

Fixes are in these three commits:
https://github.com/thirtybees/community-theme-default/commit/c7c317123325aacf6096296d4b06b735adf8eb06
https://github.com/thirtybees/community-theme-default/commit/543bdc63290b3297287d0d343c39e84e212cce7c
https://github.com/thirtybees/community-theme-default/commit/0217d3a5fdf68ea66bde571ca8acff66f9cb43fd


JavaScript in the actual module is pretty broken, I'll open separate issues for each of them.

Thank you very much for reporting, @matpoppl ! And also for your patience.
