### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/blocklayered#5]
Steps to reproduce:
- Standard installation with demo products.
- Remove these overrides from the theme to use the actual module code:
  - `themes/community-theme-default/modules/blocklayered/blocklayered.tpl`
  - `themes/community-theme-default/js/modules/blocklayered/blocklayered.js`
- Go to back office -> Catalog -> Products and duplicate product *Coffee* / "demo_3" five times.
- Go to back office -> Preferences -> Products, block *Pagination* and set *Products per page* to 3.
- In front office, view category page *Coffee and Tea* to see layered navigation.
- Click on the pagination button for page 2 or page 3.

Expected result:
- Presented products of page 1 get replaced with the ones of page 2 (or 3).

Actual result:
- Nothing. Presented products don't change.

Hint: using these community theme overrides, pagination works fine. This should give a hint on what's going wrong.

**Comment by kintaro1981** [comment]
I noticed that my problem is still there if I try to filter with blocklayered the ROOT category that includes all the other categories.

In case I filter a sub-category the block layered works correctly.

**Comment by Traumflug** [comment]
Fixed by applying ksimunovic@5736fe4acf90661bb009ee45acceeb7f0e97cefd. Thank you for the work.

If there's anything left, please don't hesitate to open another issue. But also be aware that module JavaScript usually gets overridden by a like-named file in the theme. If something doesn't work there, the theme file needs fixing. An alternative is to try simply removing the like-named file in the theme, to use JavaScript provided by the module.
