### ISSUE TITLE
Category products sorting issues.

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/blocklayered#6]
When module activated all products sorting go throw this module.
On category page loads the sorting is not correct like setup in back office Preferences -> Products -> Default order by (tested with: Position inside category).

This commit seems to fix it: `https://github.com/PrestaShop/blocklayered/commit/d921395391131d3a470a5cb22084d33b751c1147`

Even with this commit applied, when changing price slider and returning to original slide range (0-....) the sorting breaks again.
This commit claims to fix it:
`https://github.com/PrestaShop/blocklayered/pull/119/commits/6deba5580ab28ca7ff1e2b8e478d3f46bc757943`

Due to lack of time I am only able to submit the ticket instead of checking it myself.

**Comment by Traumflug** [comment]
Apparently fixed together with #5. Please don't hesitate to re-open this issue if it didn't.
